import {Student} from '../_models/student';

export const STUDENT_DATA: Student[] = [
  {
    name: 'Sofie van Leeuwen',
    team: 'U.T.V.',
    amount: 8.06,
    travel: 'Skeeleren',
    amountRaised: 511,
    description: 'Rollen tot je een ons weegt.\n' +
      'Alles voor het goede doel!\n',
    imageSource: 'assets/runs/run_sofie_van_leeuwen.png',
    imageaction: 'assets/action_run/action_sofie_van_leeuwen.png',
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 8.06,
    travel: 'Hardlopen',
    amountRaised: 8,
    description: '',
    imageSource: 'assets/runs/run(2)_machteld_menkveld.png',
    imageaction: null,
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 11.02,
    travel: 'Hardlopen',
    amountRaised: 11,
    description: 'Heerlijke omgeving die krommerijn.',
    imageSource: 'assets/runs/run(1)_machteld_menkveld.png',
    imageaction: 'assets/action_run/action_machteld_menkveld.png',
  },
  {
    name: 'Isabel Buitendijk',
    team: 'U.T.V.',
    amount: 55.52,
    travel: 'Fietsen',
    amountRaised: 22.18,
    description: '',
    imageSource: 'assets/runs/run_isabel_buitendijk.png',
    imageaction: null,
  },
  {
    name: 'Gijs Franken',
    team: 'SV Paramedus',
    amount: 6,
    travel: 'Wandelen',
    amountRaised: 10,
    description: '',
    imageSource: 'assets/runs/run_gijs_franken.png',
    imageaction: null,
  },
  {
    name: 'Jesse van Kammen',
    team: 'Codex',
    amount: 30,
    travel: 'Wandelen',
    amountRaised: 250,
    description: 'Shoutout me fam',
    imageSource: 'assets/runs/run_jesse_van_kammen.png',
    imageaction: 'assets/action_run/action_jesse_van_kammen.png',
  },
  {
    name: 'Mark Brouwer',
    team: 'U.T.V.',
    amount: 7.39,
    travel: 'Hardlopen',
    amountRaised: 27.27,
    description: 'SO naar Rob',
    imageSource: 'assets/runs/run_mark_brouwer.png',
    imageaction: null,
  },
  {
    name: 'Lisa de Winter',
    team: 'U.T.V.',
    amount: 5.5,
    travel: 'Hardlopen',
    amountRaised: 11,
    description: '',
    imageSource: 'assets/runs/run_lisa_de_winter_2.png',
    imageaction: null,
  },
  {
    name: 'Didier Wouters',
    team: 'Ingenium Cabo Bianci',
    amount: 7.67,
    travel: 'Wandelen',
    amountRaised: 16,
    description: '',
    imageSource: 'assets/runs/run_didier_wouters.png',
    imageaction: null,
  },
  {
    name: 'Lars Goris',
    team: 'Ingenium Cabo Bianci',
    amount: 6,
    travel: 'Wandelen',
    amountRaised: 6,
    description: '',
    imageSource: 'assets/runs/run_lars_goris.png',
    imageaction: null,
  },
  {
    name: 'Maartje Brok',
    team: 'Codex',
    amount: 11.94,
    travel: 'Wandelen',
    amountRaised: 23.88,
    description: 'Een heerlijke zondagmiddagwandeling in de zon!',
    imageSource: 'assets/runs/run_maartje_brok.png',
    imageaction: 'assets/action_run/action_maartje_brok.png',
  },
  {
    name: 'Tessa Klomp',
    team: 'Codex',
    amount: 9.33,
    travel: 'Wandelen',
    amountRaised: 18,
    description: 'De zondag starten met een lange wandeling naar de Maarsseveense plassen 🚶‍♀‍',
    imageSource: 'assets/runs/run_tessa_klomp.png',
    imageaction: 'assets/action_run/action_tessa_klomp.png',
  },
  {
    name: 'Jildou Valkema',
    team: 'U.T.V.',
    amount: 6,
    travel: 'Wandelen',
    amountRaised: 6,
    description: '',
    imageSource: 'assets/runs/run_jildou_valkema.png',
    imageaction: null,
  },
  {
    name: 'Lisa de Winter',
    team: 'U.T.V.',
    amount: 8,
    travel: 'Hardlopen',
    amountRaised: 16,
    description: 'Ik loop voor YSWR, maar mijn 8km is niks vergeleken met de hardlopers daar. ' +
      'Standaard elke zaterdag 20km rennen met elkaar. Dat noem ik pas doorzetten ❤️ ' +
      'Ooit in de verre toekomst loop ik een keer met ze mee ! #strongertogether',
    imageSource: 'assets/runs/run_lisa_de_winter.png',
    imageaction: null,
  },

];
