import {Student} from '../_models/student';

export const STUDENT_DATA: Student[] = [
  {
    name: 'Lars Goris',
    team: 'Ingenium Cabo Bianci',
    amount: 7,
    travel: 'Wandelen',
    amountRaised: 61,
    description: 'Rondje Single',
    imageSource: 'assets/runs/run_lars_goris_2.png',
    imageaction: null,
  },
  {
    name: 'Isabel Buitendijk',
    team: 'U.T.V.',
    amount: 141.79,
    travel: 'Fietsen',
    amountRaised: 71.70,
    description: '',
    imageSource: 'assets/runs/run_isabel_buitendijk_2.png',
    imageaction: null,
  },
  {
    name: 'Jildou Valkema',
    team: 'U.T.V.',
    amount: 125,
    travel: 'Fietsen',
    amountRaised: 25,
    description: '',
    imageSource: 'assets/runs/run_jildou_valkema_2.png',
    imageaction: null,
  },
  {
    name: 'Roelof Buck',
    team: 'Ingenium Cabo Bianci',
    amount: 7.36,
    travel: 'Wandelen',
    amountRaised: 66.38,
    description: '',
    imageSource: 'assets/runs/run_roelof_buck.png',
    imageaction: null,
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 4.02,
    travel: 'Hardlopen',
    amountRaised: 2,
    description: '',
    imageSource: null,
    imageaction: null,
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 8.02,
    travel: 'Hardlopen',
    amountRaised: 4,
    description: '',
    imageSource: null,
    imageaction: null,
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 4.02,
    travel: 'Hardlopen',
    amountRaised: 2,
    description: '',
    imageSource: null,
    imageaction: null,
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 8.03,
    travel: 'Hardlopen',
    amountRaised: 4,
    description: '',
    imageSource: null,
    imageaction: null,
  },
  {
    name: 'Nina de Winter',
    team: 'U.T.V.',
    amount: 20.87,
    travel: 'Hardlopen',
    amountRaised: 21,
    description: '💙 U.T.V. BEDANKT! 💛\n' +
      'Het is echt geweldig om te zien dat jullie je zo hebben ingezet voor YSWR ❤️ Speciaal bedankje voor Sofie die in haar eentje €511 heeft opgehaald, WAUW \n' +
      'Sport makes us stronger 💪🏼 #strongertogether\n',
    imageSource: 'assets/runs/run_nina_de_winter.png',
    imageaction: 'assets/action_run/action_nina_de_winter.png',
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 8,
    travel: 'Wandelen',
    amountRaised: 7.13,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_14.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 5.41,
    travel: 'Wandelen',
    amountRaised: 7.13,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_13.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 4.83,
    travel: 'Wandelen',
    amountRaised: 7.14,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_12.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 3.73,
    travel: 'Wandelen',
    amountRaised: 7.14,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_11.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 4.04,
    travel: 'Wandelen',
    amountRaised: 7.14,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_10.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 3.95,
    travel: 'Wandelen',
    amountRaised: 7.14,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_9.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 1.56,
    travel: 'Wandelen',
    amountRaised: 7.14,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_8.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 2.08,
    travel: 'Wandelen',
    amountRaised: 7.14,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_7.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 4.21,
    travel: 'Wandelen',
    amountRaised: 7.15,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_6.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 3.43,
    travel: 'Wandelen',
    amountRaised: 7.15,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_5.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 0.53,
    travel: 'Wandelen',
    amountRaised: 7.15,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_4.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 2.93,
    travel: 'Wandelen',
    amountRaised: 7.15,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_3.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 3.47,
    travel: 'Wandelen',
    amountRaised: 7.15,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_2.png',
    imageaction: null,
  },
  {
    name: 'Ilse Velkers',
    team: 'SV Paramedus',
    amount: 2.38,
    travel: 'Wandelen',
    amountRaised: 7.15,
    description: '',
    imageSource: 'assets/runs/run_ilse_velkers_1.png',
    imageaction: null,
  },
  {
    name: 'Sofie van Leeuwen',
    team: 'U.T.V.',
    amount: 15,
    travel: 'Skeeleren',
    amountRaised: 14.8,
    description: 'Rollen, rollen, rollen.',
    imageSource: 'assets/runs/run_sofie_van_leeuwen(2).png',
    imageaction: 'assets/action_run/action_sofie_van_leeuwen(2).png',
  },
  {
    name: 'Milan Dammmingh',
    team: 'Ingenium Cabo Bianci',
    amount: 5,
    travel: 'Hardlopen',
    amountRaised: 110,
    description: '',
    imageSource: 'assets/runs/run_milan_dammingh.png',
    imageaction: null,
  },
  {
    name: 'Krijn van Vliet',
    team: 'Ingenium Cabo Bianci',
    amount: 21.3,
    travel: 'Hardlopen',
    amountRaised: 30.5,
    description: '',
    imageSource: 'assets/runs/run_krijn_van_vliet.png',
    imageaction: null,
  },
  {
    name: 'Tycho Bakker',
    team: 'Ingenium Cabo Bianci',
    amount: 5,
    travel: 'Wandelen',
    amountRaised: 5,
    description: '',
    imageSource: null,
    imageaction: null,
  },
  {
    name: 'Lisa de Winter',
    team: 'U.T.V.',
    amount: 6.36,
    travel: 'Hardlopen',
    amountRaised: 12,
    description: '',
    imageSource: 'assets/runs/run_lisa_de_winter_3.png',
    imageaction: null,
  },
  {
    name: 'Jelle van Rossum',
    team: 'U.T.V.',
    amount: 30.1,
    travel: 'Hardlopen',
    amountRaised: 20.8,
    description: 'Het betreft 4 ronjes lopen in 1 keer.',
    imageSource: null,
    imageaction: null,
  },
  {
    name: 'Sofie van Leeuwen',
    team: 'U.T.V.',
    amount: 42.64,
    travel: 'Skeeleren',
    amountRaised: 511,
    description: 'Rollen tot je een ons weegt.\n' +
      'Alles voor het goede doel!\n',
    imageSource: 'assets/runs/run_sofie_van_leeuwen.png',
    imageaction: 'assets/action_run/action_sofie_van_leeuwen.png',
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 8.06,
    travel: 'Hardlopen',
    amountRaised: 8,
    description: '',
    imageSource: 'assets/runs/run(2)_machteld_menkveld.png',
    imageaction: null,
  },
  {
    name: 'Machteld Menkveld',
    team: 'U.T.V.',
    amount: 11.02,
    travel: 'Hardlopen',
    amountRaised: 11,
    description: 'Heerlijke omgeving die krommerijn.',
    imageSource: 'assets/runs/run(1)_machteld_menkveld.png',
    imageaction: 'assets/action_run/action_machteld_menkveld.png',
  },
  {
    name: 'Isabel Buitendijk',
    team: 'U.T.V.',
    amount: 55.52,
    travel: 'Fietsen',
    amountRaised: 22.18,
    description: '',
    imageSource: 'assets/runs/run_isabel_buitendijk.png',
    imageaction: null,
  },
  {
    name: 'Gijs Franken',
    team: 'SV Paramedus',
    amount: 6,
    travel: 'Wandelen',
    amountRaised: 10,
    description: '',
    imageSource: 'assets/runs/run_gijs_franken.png',
    imageaction: null,
  },
  {
    name: 'Jesse van Kammen',
    team: 'Codex',
    amount: 30,
    travel: 'Wandelen',
    amountRaised: 250,
    description: 'Shoutout me fam',
    imageSource: 'assets/runs/run_jesse_van_kammen.png',
    imageaction: 'assets/action_run/action_jesse_van_kammen.png',
  },
  {
    name: 'Mark Brouwer',
    team: 'U.T.V.',
    amount: 7.39,
    travel: 'Hardlopen',
    amountRaised: 27.27,
    description: 'SO naar Rob',
    imageSource: 'assets/runs/run_mark_brouwer.png',
    imageaction: null,
  },
  {
    name: 'Lisa de Winter',
    team: 'U.T.V.',
    amount: 5.5,
    travel: 'Hardlopen',
    amountRaised: 11,
    description: '',
    imageSource: 'assets/runs/run_lisa_de_winter_2.png',
    imageaction: null,
  },
  {
    name: 'Didier Wouters',
    team: 'Ingenium Cabo Bianci',
    amount: 7.67,
    travel: 'Wandelen',
    amountRaised: 16,
    description: '',
    imageSource: 'assets/runs/run_didier_wouters.png',
    imageaction: null,
  },
  {
    name: 'Lars Goris',
    team: 'Ingenium Cabo Bianci',
    amount: 6,
    travel: 'Wandelen',
    amountRaised: 6,
    description: '',
    imageSource: 'assets/runs/run_lars_goris.png',
    imageaction: null,
  },
  {
    name: 'Maartje Brok',
    team: 'Codex',
    amount: 11.94,
    travel: 'Wandelen',
    amountRaised: 23.88,
    description: 'Een heerlijke zondagmiddagwandeling in de zon!',
    imageSource: 'assets/runs/run_maartje_brok.png',
    imageaction: 'assets/action_run/action_maartje_brok.png',
  },
  {
    name: 'Tessa Klomp',
    team: 'Codex',
    amount: 9.33,
    travel: 'Wandelen',
    amountRaised: 18,
    description: 'De zondag starten met een lange wandeling naar de Maarsseveense plassen 🚶‍♀‍',
    imageSource: 'assets/runs/run_tessa_klomp.png',
    imageaction: 'assets/action_run/action_tessa_klomp.png',
  },
  {
    name: 'Jildou Valkema',
    team: 'U.T.V.',
    amount: 6,
    travel: 'Wandelen',
    amountRaised: 6,
    description: '',
    imageSource: 'assets/runs/run_jildou_valkema.png',
    imageaction: null,
  },
  {
    name: 'Lisa de Winter',
    team: 'U.T.V.',
    amount: 8,
    travel: 'Hardlopen',
    amountRaised: 16,
    description: 'Ik loop voor YSWR, maar mijn 8km is niks vergeleken met de hardlopers daar. ' +
      'Standaard elke zaterdag 20km rennen met elkaar. Dat noem ik pas doorzetten ❤️ ' +
      'Ooit in de verre toekomst loop ik een keer met ze mee ! #strongertogether',
    imageSource: 'assets/runs/run_lisa_de_winter.png',
    imageaction: null,
  },

];
